baseURL = "https://maria-hugo-starter.netlify.app"
title = "Maria Kim Heinert"
theme = "PaperMod"

# Theme configuration
[params]
env = "production"
author = "Maria Kim Heinert"
description = "Portfolio description"
keywords = ["Blog", "Portfolio", "PaperMod"]
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableScrollToTop = false

[params.label]
text = "Home"
icon = "/profile.png"
iconHeight = 24

[params.profileMode]
enabled = true
title = "Maria Kim Heinert"
subtitle = "I am a teacher."
imageUrl = "profile.png"
imageWidth = 120
imageHeight = 120

[[params.socialIcons]]
name = "github"
url = "https://github.com/mariakimheinert"

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "about"
name = "about me"
url = "/about"
weight = 30
